### ISSUE TITLE
Shroud of Silent Mist's special rule "Slow and Silent Death" is not factored into Time Passes

### ISSUE THREAD

**Issue by Sypwn** [spirit-island/spirit-island-mod#118]
Shroud of Silent Mist's special rule "Slow and Silent Death" states:
"Invaders and Dahan in your lands don't heal Damage."
Yet when the "Time Passes" button is pressed, they are still healed automatically, and I don't see any tools to prevent that. Thus we have to essentially take a snapshot of the board each time so we can revert damage.

**Comment by iakona** [comment]
When you pick Shroud as a spirit, there's a message shown on screen and in chat to the player for how to prevent healing during time passes. It's also documented in the tips doc as well https://github.com/spirit-island/spirit-island-mod/blob/beta/TIPS.md#specific-effects
