### ISSUE TITLE
Incarna on top of spirit panels do not get tinted when the spirit is chosen.

### ISSUE THREAD

**Issue by pyrrhicPachyderm** [spirit-island/spirit-island-mod#168]
The code to tint Incarna appears in the section to handle objects in the spirit bag but not in the section to handle objects on top of the board.

Tinting Incarna happens here:
https://github.com/spirit-island/spirit-island-mod/blob/60aca3e7243bc0fb735435222f7aa1ce9d36e3b1/objects/SourceSpirit/script.lua#L355-L356

But is missing from here:
https://github.com/spirit-island/spirit-island-mod/blob/60aca3e7243bc0fb735435222f7aa1ce9d36e3b1/objects/SourceSpirit/script.lua#L376-L404

**Comment by iakona** [comment]
should be fixed with https://github.com/spirit-island/spirit-island-mod/commit/37aeb0d5ee9f2dd6c144a075a808f7d33cdb99af
