### ISSUE TITLE
Update power editor to allow tagging.

### ISSUE THREAD

**Issue by tomprince** [spirit-island/spirit-island-mod#22]
From https://github.com/spirit-island/spirit-island-mod/pull/19#pullrequestreview-584800737:
> While outside of the scope of the current review, i'd like to see a PR for updating the power editor to support the ability to add tags to powers as well

**Comment by iakona** [comment]
Added this in https://github.com/spirit-island/spirit-island-mod/commit/2a64bfb01fbb6f9bf63a1f8b5c845e6e6439af00
