### ISSUE TITLE
Reminder tokens are missing.

### ISSUE THREAD

**Issue by tomprince** [spirit-island/spirit-island-mod#32]
There should be reminder tokens available for things that are not defend or isolate. (Skip actions, weave together the fabric of place, dahan invulnerability, quicksand, etc). When the isolate tokens were moved to a bag, the generic reminder tokens were lost.

I also found having reminder tokens near the spirit board (as they originally were laid out, and where they were cleaned up in #16) really handy for marking which growth options and innates had been used; I think it is much less convenient to grab them from the element tracker row. I don't think a hot key helps, as I'm running out of free keys to bind.

**Comment by iakona** [comment]
the reminder/generic side are on the back side of defend and isolate tokens. like how they were before, and also are IRL
