### ISSUE TITLE
Invader UI doesn't properly handle having 3 or more cards in a spot.

### ISSUE THREAD

**Issue by tomprince** [spirit-island/spirit-island-mod#64]
It doesn't necessarily need to display all the cards (though maybe that would be possible through `setXmlTable` and constructing the panels all explicitly), but it should at least indicate when it can't show things. Right now, it displays a grey bar, instead, which could easily be mistaken for mountains.

**Comment by iakona** [comment]
iirc it used to display the text "EMPTY" but MJ didn't like that text being there so that was removed

**Comment by tomprince** [comment]
It should probably at least say something like "TOO MANY" and not just grey bars.

**Comment by iakona** [comment]
fixed with c055780
